version: '3.1'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    command: /bin/sh
    volumes:
      - dependencies:/app/node_modules
      - .:/app

volumes:
  dependencies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules
  